# Generated by Django 4.0.4 on 2022-05-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='pub_date',
            new_name='created_at',
        ),
    ]
